# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-13 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapPoi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_num', models.IntegerField()),
                ('name_id', models.IntegerField()),
                ('address', models.CharField(blank=True, max_length=400)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('precise', models.BooleanField()),
                ('level', models.CharField(max_length=100)),
                ('food', models.IntegerField()),
                ('hotel', models.IntegerField()),
                ('shopping', models.IntegerField()),
                ('dailyservice', models.IntegerField()),
                ('entertainment', models.IntegerField()),
                ('education', models.IntegerField()),
                ('medical', models.IntegerField()),
                ('financial', models.IntegerField()),
                ('traffic', models.IntegerField()),
            ],
        ),
    ]
