# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-15 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappoi',
            name='score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
